# Generated by Django 3.2.13 on 2023-09-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postion',
            new_name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='blog',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
