# Generated by Django 3.2.13 on 2023-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog',
            field=models.URLField(blank=True),
        ),
    ]
