# Generated by Django 3.2.13 on 2023-09-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='immunity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='week_studytime',
            field=models.IntegerField(default=0),
        ),
    ]
