# Generated by Django 3.2.13 on 2023-10-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='individual_rule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
