# Generated by Django 3.2.13 on 2023-09-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='individual_rule',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
