# Generated by Django 3.2.13 on 2023-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_alter_user_individual_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytimer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studytimer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
