# Generated by Django 3.2.13 on 2023-10-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_alter_user_individual_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
