# Generated by Django 3.2.13 on 2023-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_alter_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
