# Generated by Django 3.2.13 on 2023-09-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_auto_20230920_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='individual_rule',
        ),
    ]
