# Generated by Django 3.2.13 on 2023-09-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_alter_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='immunity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='penalty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='week_studytime',
            field=models.IntegerField(null=True),
        ),
    ]
