# Generated by Django 3.2.13 on 2023-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0003_auto_20231003_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studytimer',
            name='date',
            field=models.DateField(),
        ),
    ]
