# Generated by Django 3.2.13 on 2023-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0004_auto_20231004_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(),
        ),
    ]
