# Generated by Django 3.2.13 on 2023-10-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0005_auto_20231004_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='individual_rule',
        ),
    ]
