# Generated by Django 3.2.13 on 2023-09-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
