# Generated by Django 3.2.13 on 2023-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0006_remove_user_individual_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='confirm',
            field=models.IntegerField(default=1),
        ),
    ]
