# Generated by Django 3.2.13 on 2023-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0008_alter_money_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
