# Generated by Django 3.2.13 on 2023-10-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0009_alter_money_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.CharField(choices=[('출석', '출석'), ('일정', '일정')], default='', max_length=2),
        ),
    ]
