# Generated by Django 3.2.13 on 2023-10-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0009_alter_money_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
